name: ğŸ” 4th lvl reusable workflow
on:
  workflow_call: {}

jobs:
  fourth-level-reusable-wf-job:
    name: ğŸ” 4th lvl reusable workflow job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run script
        run: |
          echo "Hello, world!"

  fifth-level-reusable-wf:
    name: Fifth level reusable workflow
    uses: ./.github/workflows/fifth.yaml
